[build]
builder = "NIXPACKS"

[phases.setup]

[phases.build]
cmd = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[phases.release]
cmd = "sh railway/init-app.sh"

[start]
cmd = "php artisan serve --host 0.0.0.0 --port ${PORT:-8080}"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
